print ("Acá estuvo el profesor Joel Partida. Saludos a todos")
print ("Esto es un primer cambio hecho por Joel Partido y revisado por Joel Partida")
print ("estoy haciendo esto en clases Luciano Campanella)
print("Hola me llamo Luciano Balot y este es mi primer cambio.")
print("Estoy en clase haviendo codigo y soy Mikeas Correa.")
print("Soy MAria Eugenia Losada")
print("Hola me llamo Luciano Balot y este es mi primer cambio.")
print(" es mi primer commit")
print("Primer cambio Gabriel Ponce")
print("mi primer cambio Wanda Suarez")
print("mi primer cambio Matias Dittler")
