print ("Acá estuvo el profesor Joel Partida. Saludos a todos")
print ("Esto es un primer cambio hecho por Joel Partido y revisado por Joel Partida")
print ("escribi mi nombre Marcos Bayon")
print("Esto es un primer cambio hecho por Joel Partido y revisado por Joel Partida")
print("hecho en clase, joaquin hernandez")
print ("Esto es un primer cambio hecho por Joel Partido y revisado por Joel Partida")
print("Primer cambio Gabriel Ponce")
print("Acá Nico Valenciano. Un saludo para todos los que me conocen")
print("Hola, soy camila piergentili")
print ("Acá estuvo la alumna Critina Morales. Saludos a todos")
print ("Esto es un primer cambio hecho por Joel Partido y revisado por Joel Partida")
print ("Acá estuvo Juan Chaparro.")
print("Estoy en clase haviendo codigo y soy Mikeas Correa.")
print("Soy MAria Eugenia Losada")
print("Hola me llamo Luciano Balot y este es mi primer cambio.")
print(" es mi primer commit")
print("Estoy escribiendo, soy Bruno")
print("Primer cambio Gabriel Ponce")
print("cambio de Camila Piergentili")
print("mi primer cambio Wanda Suarez")
print("cambio por Emiliano Correa")
print ("estoy haciendo esto en clase y mi nombre es Daniel D'Onofrio")
print ("Facundo Reiseng commit")
print("Soy Pedro Weyland. :)")
